<?php

namespace Tests\Feature\Http\Controllers\Api\Settings\Module\Rmsapi;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Api\Settings\Module\Rmsapi\RmsapiConnectionController
 */
class RmsapiConnectionControllerTest extends TestCase
{


    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

$rmsapiConnection = factory(\App\Models\RmsapiConnection::class)->create();

$response = $this->delete(route('connections.destroy', ['connection' => $rmsapiConnection->connection]));

$response->assertOk();
$this->assertDeleted($connections);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



$response = $this->get(route('connections.index'));

$response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



$response = $this->post(route('connections.store'), [
            // TODO: send request data
        ]);

$response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
