<?php

namespace Tests\Feature\Http\Controllers\Api\Settings\Module\Printnode;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Api\Settings\Module\Printnode\PrinterController
 */
class PrinterControllerTest extends TestCase
{


    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



$response = $this->get(route('module.printnode.printers.index'));

$response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
