<?php

namespace Tests\Feature\Http\Controllers\Api\Run;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Api\Run\SyncApi2CartController
 */
class SyncApi2CartControllerTest extends TestCase
{


    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



$response = $this->get(route('api2cart.index'));

$response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
