<?php

namespace Tests\Feature\Http\Controllers\Order;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Order\PacksheetController
 */
class PacksheetControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



$response = $this->get(route('packsheet.show', ['packsheet' => $packsheet]));

$response->assertOk();
$response->assertViewIs('autopilot.packsheet');
$response->assertViewHas('order_number');

        // TODO: perform additional assertions
    }

    // test cases...
}
