<?php

namespace Tests\Feature\Http\Controllers\Api\Order;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Api\Order\OrderProductController
 */
class OrderProductControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');



$response = $this->get(route('order.products.index'));

$response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
$this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

$product = factory(\App\Models\Product::class)->create();

$response = $this->put(route('order.products.update', [$product]), [
            // TODO: send request data
        ]);

$response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
